version: '3.4'

services:
  app1:
    image: nginxtutorial
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      APP_NAME: app1
    ports:
      - 3000:3000

  app2:
    image: nginxtutorial_app2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      APP_NAME: app2
    ports:
      - 3001:3000

  app3:
    image: nginxtutorial_app3
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      APP_NAME: app3
    ports:
      - 3002:3000
